steps:
  # Step 1: Build the Docker image with the commit hash as the tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/thinking-leaf-454010-i2/my-model-repo/hello-world:$SHORT_SHA', '.']
    env:
      - 'PROJECT_ID=thinking-leaf-454010-i2'
      - 'LOCATION=us-central1'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/thinking-leaf-454010-i2/my-model-repo/hello-world:$SHORT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying commit hash: $SHORT_SHA to Cloud Run"

        # Enable Artifact Registry authentication for Cloud Run
        gcloud auth configure-docker us-central1-docker.pkg.dev

        # Deploy the service to Cloud Run
        gcloud run deploy hello-world-service \
          --image=us-central1-docker.pkg.dev/thinking-leaf-454010-i2/my-model-repo/hello-world:$SHORT_SHA \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --project=thinking-leaf-454010-i2

options:
  logging: CLOUD_LOGGING_ONLY
