
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-hello-world
  name: node-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-hello-world
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/thinking-leaf-454010-i2/my-model-repo/hello-world:$SHORT_SHA     
        name: node-hello-world
        resources: {}
status: {}
